Modules/AdminJobDescription/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin/job-descriptions', 'as' => 'admin.', 'middleware' => 'auth:admin'], function () {
    Route::get('/', 'AdminJobDescriptionController@index')->name('job-descriptions.index')->middleware('can:view-job-descriptions');
    Route::get('/create', 'AdminJobDescriptionController@create')->name('job-descriptions.create')->middleware('can:create-job-descriptions');
    Route::post('/create', 'AdminJobDescriptionController@store')->name('job-descriptions.store')->middleware('can:create-job-descriptions');
    Route::get('/{id}/edit', 'AdminJobDescriptionController@edit')->name('job-descriptions.edit')->middleware('can:edit-job-descriptions');
    Route::post('/{id}/edit', 'AdminJobDescriptionController@update')->name('job-descriptions.update')->middleware('can:edit-job-descriptions');
    Route::post('/{id}/delete', 'AdminJobDescriptionController@destroy')->name('job-descriptions.destroy')->middleware('can:delete-job-descriptions');
    Route::get('/{id}/show', 'AdminJobDescriptionController@show')->name('job-descriptions.show')->middleware('can:create-job-descriptions');
});

Modules/AdminJobDescription/Http/Controllers/AdminJobDescriptionController.php
<?php

namespace Modules\AdminJobDescription\Http\Controllers;

use App\Helpers\Permission;
use App\Models\JobDescription;
use App\Traits\Slugger;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Log;

class AdminJobDescriptionController extends Controller
{
    use Slugger;

    private $indexRoute;

    private $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
        $this->indexRoute = route('admin.job-descriptions.index');
    }

    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $data['pageTitle'] = "Job Description Management";
        $data['jobs'] = JobDescription::paginate(20);

        return view('adminjobdescription::index', $data);
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $data['pageTitle'] = "Add Job Description";
        $data['breadcrumbs'] = '<li><a href="' . route('admin.job-descriptions.index') . '">Course Management</a></li><li>Add</li>';
        return view('adminjobdescription::create', $data);
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store()
    {
        $this->request->validate([
            'name' => 'required',
            'description' => 'required'
        ]);

        try {
            $data = $this->request->only('name', 'description', 'status');
            // $data['slug'] = $this->createSlug($this->request->name, JobDescription::class);

            JobDescription::create($data);

            session()->flash('success_message', __('alerts.create_success'));
        } catch (\Exception $e) {
            Log::info($e->getMessage());
            session()->flash('error_message', __('alerts.create_error'));
        }

        return redirect()->to($this->indexRoute);
    }

    /**
     * Show the specified resource.
     * @param int $id
     * @return Response
     */
    public function show($course_id)
    {
        $data = [];
        $data['breadcrumbs'] = '<li><a href="' . route('admin.job-descriptions.index') . '">Job Desctiption</a></li><li>Detail</li>';
        $data['job'] = JobDescription::find($course_id);
        return view('adminjobdescription::show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $data['pageTitle'] = "Edit Course";
        $data['job'] = $this->getJobDescriptionById($id);
        $data['jobs'] = JobDescription::where('status', 1)->get();
        $data['breadcrumbs'] = '<li><a href="' . route('admin.job-descriptions.index') . '">Job Description Management</a></li><li>Edit</li>';

        return view('adminjobdescription::edit', $data);
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update($id)
    {
        $this->request->validate([
            'name' => 'required',
            'description' => 'required'
        ]);

        try {
            $data = $this->request->only('name', 'description', 'status');

            // $data['slug'] = $this->createSlug($this->request->name, JobDescription::class);

            $job = JobDescription::find($id);

            $job->update($data);

            session()->flash('success_message', __('alerts.update_success'));
        } catch (\Exception $e) {
            session()->flash('error_message', __('alerts.update_error'));
        }

        return redirect()->to($this->indexRoute);
    }

    /**
     * Remove the specified resource from storage.
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        try {

            $job = $this->getJobDescriptionById($id);

            if ($job->status == 1) {
                session()->flash('error_message', __('alerts.delete_error_active'));
                return redirect()->to($this->indexRoute);
            }

            $job->delete();
            session()->flash('success_message', __('alerts.delete_success'));
        } catch (\Exception $e) {
            session()->flash('error_message', __('alerts.delete_error'));
        }

        return redirect()->to($this->indexRoute);
    }

    private function getJobDescriptionById($id)
    {
        return JobDescription::find($id);
    }
}

Modules/AdminJobDescription/Resources/views/create.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row">
    <div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Add Job Description
                    <button class="btn btn-sm btn-primary pull-right panel-btn" onclick="window.history.go(-1);">
                        <i class="fas fa-long-arrow-alt-left"></i> Back
                    </button>
                </h3>
            </div>
            <!--Hover Rows-->
            <!--===================================================-->
            <form class="form-horizontal" id="add-course" action="{{ route('admin.job-descriptions.store') }}" method="POST"
                  enctype="multipart/form-data">
                @csrf
                <div class="panel-body">
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="">Name <span
                                    class="required_color">*</span></label>
                        <div class="col-sm-9">
                            <input type="text" placeholder="Name" name="name" value="{{ old('name') }}" id="input-name"
                                   class="form-control" >
                            @if($errors->has('name'))
                            <small class="help-block text-danger">{{ $errors->first('name')}}</small>
                            @endif
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                        <label class="col-md-2 control-label">Publish</label>
                        <div class="col-md-9">
                            <div class="radio">

                                <!-- Inline radio buttons -->
                                <input id="input-status" class="magic-radio" type="radio" name="status" value="1" <?= ((old('status') == 1)? 'checked':''); ?>>
                                <label for="input-status">Yes</label>

                                <input id="input-status-2" class="magic-radio" value="0" type="radio" name="status" <?= ((old('status') == 0)? 'checked':''); ?>>
                                <label for="input-status-2">No</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="demo-contact-input">Description <span
                                    class="required_color">*</span></label>
                        <div class="col-md-10">
                            <textarea name="description" id="input-description" cols="30" rows="10" class="form-control ckeditor">{{ old('description') }}</textarea>
                        <small class="help-block text-danger">{{ $errors->first('description')}}</small>
                        </div>
                    </div>
                    <!-- <div class="form-group">
                        <label class="col-md-3 control-label" for="demo-contact-input">Status</label>
                        <div class="col-md-10">
                            <div class="radio">
                                <input id="status" class="magic-radio" type="radio" name="status" value="1"
                                       checked>
                                <label for="status" style="color:#000000;">YES</label>
                                <input id="status-2" class="magic-radio" type="radio" name="status"
                                       value="0">
                                <label for="status-2" style="color:#000000;">NO</label>
                            </div>
                        </div>
                    </div> -->
                    <div class="form-group">
                        <div class="col-lg-2 col-sm-12 col-xs-12 pull-right">
                            <button class="btn btn-block btn-success" type="submit">Create</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    $(function() {
        $("#add-course").on('submit', function(course) {
            $(this).find("button[type='submit']").prop('disabled', true).html('<i class="fas fa-spinner fa-spin"></i> Creating...');
        });
    });
</script>
@endpush

Modules/AdminJobDescription/Resources/views/edit.blade.php
@extends('admin.layouts.master')
@section('content')

<div class="row">
    <div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Edit Job Description
                    <a href="{{ route('admin.job-descriptions.index') }}" class="btn panel-btn btn-sm btn-primary pull-right"style="margin-top: 15px; margin-right: 15px;"> <i class="fas fa-long-arrow-alt-left"></i> Back</a>
                </h3>
            </div>
            <form class="form-horizontal" action="{{ route('admin.job-descriptions.update',$job->id) }}"
                  method="POST" enctype="multipart/form-data">
                @csrf
                <div class="panel-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-name">Name <span
                                    class="required_color">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="Name" name="name" value="{{ old('name',$job->name) }}"
                                   id="input-name" class="form-control" required="required">
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                        <label class="col-md-2 control-label">Publish</label>
                        <div class="col-md-9">
                            <div class="radio">

                                <!-- Inline radio buttons -->
                                <input id="input-status" class="magic-radio" type="radio" name="status" value="1" {{ $job->status ? 'checked' :'' }}>
                                <label for="input-status">Yes</label>

                                <input id="input-status-2" class="magic-radio" value="0" type="radio" name="status" {{ $job->status == 0 ? 'checked' : '' }}>
                                <label for="input-status-2">No</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                        <label class="col-md-2 control-label" for="input-description">Description <span
                                    class="required_color">*</span></label>
                        <div class="col-md-10">
                            <textarea name="description" id="input-description" cols="30" rows="10" class="form-control ckeditor">{{ old('description',$job->description) }}</textarea>
                            @if($errors->has('description'))
                            <small class="help-block text-danger">{{ $errors->first('description')}}</small>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-2 col-xs-12 col-md-12 pull-right">
                            <button class="btn btn-block btn-primary" type="submit">Update</button>
                        </div>
                    </div>
                </div>
            </form>
            <!--===================================================-->
            <!--End Hover Rows-->
        </div>
    </div>
</div>
@endsection

Modules/AdminJobDescription/Resources/views/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Job Description Management
                    <a href="{{ route('admin.job-descriptions.create') }}" class="btn btn-primary btn-sm panel-btn pull-right"><i class="fa fa-plus"></i> Add Job Dscription</a>
                </h3>
            </div>

            <!-- Striped Table -->
            <!--===================================================-->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
	                            <th>S.N</th>
	                            <th>Name</th>
                                <th>Published</th>
	                            <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($jobs as $job)
	                    	    <tr>
	                    	        <td>{{ $loop->iteration }}</td>
	                    	        <td>{{ $job->name }}</td>
	                    	        <td>{!! $job->status ? "<span class='label label-success'>Active</span>" : "<span class='label label-danger'>Inactive</span>"!!}</td>
	                    	        <td>
	                    	            <a href="{{ route('admin.job-descriptions.edit',$job->id) }}" class="btn btn-sm btn-primary" title="Edit">
	                    	                <i class="fas fa-edit"></i>
                                        </a>
                                        {{-- <a href="{{ route('admin.job-descriptions.trainings.index',$job->id) }}" class="btn btn-sm btn-primary" title="Trainings">
                                            <i class="fas fa-network-wired"></i> Trainings
                                        </a> --}}
	                    	            <a href="#" title="Remove" class="btn btn-sm btn-danger btn-delete"
	                    	               data-toggle="modal"
	                    	               data-id="{{ $job->id }}"
	                    	               data-target="#delete-modal">
	                    	                <i class="fas fa-trash"></i>
                                        </a>
                                        {{-- <a href="{{ route('admin.job-descriptions.candidates',$job->id) }}" class="btn btn-sm btn-success" title="Candidates">
                                            <i class="fas fa-users"></i> Candidates
                                        </a> --}}
                                        {{-- <a href="{{ route('admin.job-descriptions.assessment',$job->id) }}" class="btn btn-sm btn-primary" title="Trainings">
                                            <i class="fas fa-network-wired"></i> Test & Assessment
                                        </a> --}}
                                        {{-- <a href="{{ route('admin.job-descriptions.show',$job->id) }}" class="btn btn-sm btn-primary" title="Details">
                                            <i class="fas fa-list"></i> Details
                                        </a> --}}
	                    	        </td>
	                    	    </tr>
                            @empty
                    	    <tr>
                    	        <td colspan="10">
                    	            <em>No data available in table ...</em>
                    	        </td>
                    	    </tr>
                            @endforelse
                        </tbody>
                    </table>
                    {!! $jobs->render() !!}
                </div>
            </div>
            <!--===================================================-->
            <!-- End Striped Table -->

        </div>
    </div>
    @include('admin.elements.delete-modal')
</div>
@endsection
@push('scripts')
    <script type="text/javascript">
        $(document).on('click','.btn-delete', function () {
            var route = '{{ route("admin.job-descriptions.destroy", ":id") }}';

            route = route.replace(':id', $(this).attr('data-id'));

            $('#delete-modal').find('form').attr('action', route);
            $('#delete-modal').modal('show');

            $('#delete-final').click(function (e) {
                $(this).attr('disabled',true);
                $(this).html('<i class="fas fa-spinner fa-spin"></i> Please wait...');
                $(this).closest('form').submit();
            });
        });
    </script>
@endpush