Modules/EmailTemplate/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth:admin'], function () {

    // EMAIL TEMPLATES
    Route::get('email-templates', 'EmailTemplateController@emailTemplate')
        ->name('email.template')
        ->middleware('can:email-template');


    Route::get('email-templates/{id}/edit', 'EmailTemplateController@edit')
        ->name('email-template.edit');

    Route::post('email-templates/{id}/edit', 'EmailTemplateController@update')
        ->name('email-template.update')
        ->middleware('can:email-template');
});

Modules/EmailTemplate/Http/Controllers/EmailTemplateController.php
<?php

namespace Modules\EmailTemplate\Http\Controllers;

use App\Helpers\Setting;
use App\Models\EmailTemplate;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

class EmailTemplateController extends Controller
{
    public function emailTemplate()
    {
        $data['pageTitle'] = "Email Management";
        $data['breadcrumbs'] = '<li>Email Templates</li>';
        $data['templates'] = EmailTemplate::get();

        return view('emailtemplate::index', $data);
    }

    public function edit($id)
    {
        $data['pageTitle'] = "Edit Email Template";
        $data['breadcrumbs'] = '<li><a href="' . route('admin.email.template') . '">Email Templates</a></li><li>Edit</li>';
        $data['title'] = "General Configuration - " . Setting::get('siteconfig')['system_name'];
        $data['side_nav'] = 'master_config';
        $data['side_sub_nav'] = 'email_template';

        $template = $this->getTemplateById($id);

        if(!$template){
            session()->flash('success_message',__('alerts.show_error'));

            return redirect()->route('admin.email.template');
        }

        $data['template'] = $template;

        return view('emailtemplate::edit',$data);
    }

    public function update(Request $request, $id)
    {
        $request->validate([
           'title' => 'required',
           'subject' => 'required',
           'description' => 'required'
        ]);

        try{

            $data = $request->only('title','subject','description');

            $template = $this->getTemplateById($id);

            $template->update($data);

            session()->flash('success_message',__('alerts.update_success'));
        }catch (\Exception $e){
            session()->flash('error_message',__('alerts.update_error'));
        }

        return redirect()->back();
    }

    private function getTemplateById($id){
        return EmailTemplate::find($id);
    }
}

Modules/EmailTemplate/Resources/views/edit.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row">
	<div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Edit Template
                	<button class="btn btn-sm btn-primary pull-right panel-btn" onclick="window.history.go(-1);">
                	    <i class="fas fa-long-arrow-alt-left"></i> Back
                	</button>
                </h3>
            </div>

            <!--Horizontal Form-->
            <!--===================================================-->
            <form action="{{ route('admin.email-template.update',$template->id ) }}" method="POST" class="panel-body form-horizontal form-padding">
                @csrf
                <div class="panel-body">
					 <div class="form-group">
					     <label class="col-md-2 control-label" for="admin-first-name">Title <span class="required_color">*</span></label>
					     <div class="col-md-4">
					         <input type="text" name="title" class="form-control" value="{{ old('title') ? old('title') : $template->title }}" placeholder="Title" >
					         <small class="help-block text-danger">{{$errors->first('title')}}</small>
					     </div>
					 </div>

					 <div class="form-group">
					     <label class="col-md-2 control-label" for="admin-first-name">Subject <span class="required_color">*</span></label>
					     <div class="col-md-4">
					         <input type="text" name="subject" class="form-control" value="{{ old('subject') ? old('subject') : $template->subject }}" placeholder="Title" >
					         <small class="help-block text-danger">{{$errors->first('subject')}}</small>
					     </div>
					 </div>

					 <div class="form-group">
					     <label class="col-md-2 control-label" for="admin-first-name">Preview <span class="required_color">*</span></label>
					     <div class="col-md-9" style="height: auto;">
					         <textarea name="description" class="form-control" id="ckeditor_fullpage">{!! $template->description !!}</textarea>
					         <small class="help-block text-danger">{{$errors->first('description')}}</small>
					         <small class="help-block text-danger" style="font-weight: bold;font-size: 13px;">
					             Note : Texts inside [[ ]] brackets are the placeholders and system reserved and you cannot change or edit them.
					         </small>
					     </div>
					 </div>
                </div>
                <div class="panel-footer text-right">
                	<div class="row">
		                <div class="col-lg-11">
		                    <button class="btn btn-sm btn-mint" type="submit">Update</button>
		                </div>
                	</div>
                </div>
            </form>
            <!--===================================================-->
            <!--End Horizontal Form-->

        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    CKEDITOR.replace('ckeditor_fullpage', { // ckeditor with full page editing : eg Email Template
        fullPage: true,
        allowedContent: true,
        extraPlugins: 'docprops',
        contentsCss: 'html {overflow:scroll;}'
    });
</script>
@endpush

Modules/EmailTemplate/Resources/views/index.blade.php
@extends('admin.layouts.master')
@section('content')

<div class="row">
    <div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Email Templates
                    <!-- <a href="{{ route('admin.employees.create') }}" class="btn btn-primary btn-sm panel-btn pull-right"><i class="fa fa-plus"></i> Add Employee</a> -->
                </h3>
            </div>

            <!-- Striped Table -->
            <!--===================================================-->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
	                            <th>S.N</th>
	                            <th>Template</th>
	                            <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	@forelse($templates as $k => $template)
                        	    <tr>
                        	        <td>{{ ++$k }}</td>
                        	        <td>{{ $template->title }}</td>
                        	        <td>
                        	            <a class="btn btn-sm btn-info" href="{{ route('admin.email-template.edit',$template->id) }}">
                        	                <i class="fas fa-edit"></i>
                        	            </a>
                        	        </td>
                        	    </tr>
                        	@empty
                    	    <tr>
                    	        <td colspan="5">
                    	            <em>No data available in table ...</em>
                    	        </td>
                    	    </tr>
                        	@endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <!--===================================================-->
            <!-- End Striped Table -->

        </div>
    </div>
</div>
@endsection