Modules/AdminUser/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin/users', 'as' => 'admin.', 'middleware' => 'auth:admin'], function() {

    // Users
    Route::get('/', 'AdminUserController@userLists')
        ->name('user.list')
        ->middleware('can:view-users');

    Route::get('add', 'AdminUserController@userAdd')
        ->name('user.add')
        ->middleware('can:create-users');

    Route::post('store','AdminUserController@userStore')
        ->name('user.store')
        ->middleware('can:create-users');

    Route::get('edit/{id}', 'AdminUserController@userEdit')
        ->name('user.edit')
        ->middleware('can:edit-users');

    Route::post('update', 'AdminUserController@userUpdate')
        ->name('user.update')
        ->middleware('can:edit-users');

    Route::post('{id}/destroy', 'AdminUserController@userDestroy')
        ->name('user.destroy')
        ->middleware('can:delete-users');

    Route::post('password-reset-user', 'AdminUserController@passwordResetUser')
        ->name('user.password-reset-user')
        ->middleware('can:edit-users');

    // Route : Profile Update
    Route::get('profile', 'AdminUserController@profile')
        ->name('user.profile');

    Route::post('profile/store', 'AdminUserController@profileStore')
        ->name('user.profile.store');

    // Route : Change Password
    Route::get('password-reset','AdminUserController@passwordReset')
        ->name('user.password-reset');

    Route::post('password-reset/store','AdminUserController@passwordResetStore')
        ->name('user.password-reset.store');

    // User Groups
    Route::get('groups', 'AdminUserController@groups')
        ->name('user.groups')
        ->middleware('can:view-groups');

    Route::post('groups/store', 'AdminUserController@groupStore')
        ->name('user.groups.store')
        ->middleware('can:create-groups');

    Route::get('groups/edit/{id}', 'AdminUserController@groupsEdit')
        ->name('user.groups.edit')
        ->middleware('can:edit-groups');

    Route::post('groups/update', 'AdminUserController@groupsUpdate')
        ->name('user.groups.update')
        ->middleware('can:edit-groups');

    Route::post('groups/destroy/{id}','AdminUserController@groupDestroy')
        ->name('user.groups.destroy')
        ->middleware('can:delete-groups');

    Route::get('groups/permission/{id}', 'AdminUserController@groupPermission')
        ->name('user.groups.permission')
        ->middleware('can:edit-groups');

    Route::post('groups/permission-store', 'AdminUserController@groupPermissionStore')
        ->name('user.groups.permission-store')
        ->middleware('can:edit-groups');

});

Modules/AdminUser/Resources/views/group.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row">
    <div class="col">
                    @include('adminuser::header_tab')
                    <div class="panel">


                        <div class="panel-body">
                            <div class="row textright searchWrapperPosition">
                                <div class="col">
                                    <div class="pageHeading">
                                        <span class="pageTitle">
                                           Groups Management
                                        </span>
                                    </div>
                                </div>
                                <hr>
                            </div>
                            <div class="row">
                                <div class="col">
                                    <table class="table table-striped table-bordered adminMgmtTable">
                                        <thead>
                                        <tr>
                                            <th>S.N</th>
                                            <th>Group Name</th>
                                            <th class="text-center">Status</th>
                                            <th>Operation</th>
                                        </tr>
                                        </thead>

                                        <tbody>

                                        <tr>
                                            <form action="{{ route('admin.user.groups.store') }}"
                                                  class="panel-body form-horizontal form-padding" method="post">
                                                {{ csrf_field() }}
                                                <td align="center"></td>

                                                <td>
                                                    <input type="text" name="name" class="form-control" value="{{ old('name') }}"
                                                           placeholder="Group Name">
                                                    <small class="help-block text-danger">{{$errors->first('name')}}</small>
                                                </td>

                                                <td class="text-center">
                                                    <div class="radio">
                                                        <input id="status" class="magic-radio" type="radio" name="status" value="1"
                                                               checked>
                                                        <label for="status" style="color:#000000;">Active</label>
                                                        <input id="status-2" class="magic-radio" type="radio" name="status" value="0">
                                                        <label for="status-2" style="color:#000000;">Inactive</label>
                                                    </div>
                                                </td>

                                                <td>
                                                    <input type="submit" class="btn btn-sm btn-block btn-primary" name="submit" value="CREATE">
                                                </td>

                                            </form>
                                        </tr>

                                        @if( count($groups) > 0 )
                                            <?php $i = 1; ?>
                                            @foreach($groups as $g)
                                                <tr>
                                                    <td align="center">{{ $i++ }} </td>
                                                    <td>
                                                        @if($g->id == config('constants.role_super_admin'))
                                                            <strong>{{ strtoupper($g->name) }}</strong>
                                                        @else
                                                            {{ $g->name }}
                                                        @endif
                                                    </td>
                                                    <td align="center">
                                                        {!!  $g->status == '1' ? '<strong style="color:green;">Active</strong>' : '<strong style="color:#bf302f;">Inactive</strong>' !!}
                                                    </td>
                                                    <td width="230">
                                                        @if($g->id == config('constants.role_super_admin'))
                                                            <span class="text-pink text-semibold">You cannot edit this user group.</span>
                                                        @else
                                                            <a href="{{ route('admin.user.groups.permission',[$g->id]) }}"
                                                               class="btn btn-sm btn-primary adminMgmtTableBtn"
                                                               title="Edit Group Permission"><i class="fa fa-cogs"></i></a>

                                                            @if(!in_array($g->id, [config('constants.php'),config('constants.php')]))
                                                                <a href="{{ route('admin.user.groups.edit',[$g->id]) }}"
                                                                   class="btn btn-sm btn-info adminMgmtTableBtn" title="Edit User Group"><i
                                                                            class="fa fa-edit"></i></a>
                                                                <a href="#" class="btn btn-sm btn-danger btn-delete"
                                                                   data-id="{{ $g->id }}"
                                                                   data-toggle="modal"
                                                                   data-target="#delete-modal">
                                                                    <i class="fa fa-trash"></i>
                                                                </a>
                                                            @endif
                                                        @endif
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @else
                                            <tr>
                                                <td align="center" colspan="10">
                                                    User Groups not found. &nbsp;
                                                </td>
                                            </tr>
                                        @endif
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
    </div>
</div>
    @include('admin.elements.delete-modal')
@stop

@push('scripts')
    <script>
        $(document).on('click', '.btn-delete', function () {
            var route = '{{ route('admin.user.groups.destroy', ':id') }}';

            route = route.replace(':id', $(this).attr('data-id'));

            $('#delete-modal').find('form').attr('action', route);
            $('#delete-modal').modal('show');

            $('#delete-final').click(function (e) {
                $(this).attr('disabled', true);
                $(this).html('<i class="fas fa-spinner fa-spin"></i> Please wait...');
                $(this).closest('form').submit();
            });
        });
    </script>
@endpush

Modules/AdminUser/Resources/views/group_edit.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="panel">
    <div class="panel-heading">
        <h3 class="panel-title">
            Update User Group
            <span class="required_fields" style="float: right;"><strong class="required_color">*</strong> These fields are required.</span>
        </h3>
    </div>

    <form action="{{ route('admin.user.groups.update') }}" method="POST" class="form-horizontal form-padding" enctype="multipart/form-data">
        <div class="panel-body">
            {{ csrf_field() }}
            <input type="hidden" name="_id" value="{{ $group_details->id }}">


            <div class="form-group">
                <label class="col-md-2 control-label" for="demo-address-input">Group Name <span class="required_color">*</span></label>
                <div class="col-md-10">
                    <input type="text" class="form-control" name="name" value="{{ old('name') ? old('name') : $group_details->name }}">
                    <small class="help-block text-danger">{{$errors->first('name')}}</small>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-2 control-label" for="demo-contact-input">Status</label>
                <div class="col-md-10">
                    <div class="radio">
                        <input id="status" class="magic-radio" type="radio" name="status" value="1" {{ $group_details->status == "1" ? "checked" : "" }}>
                        <label for="status" style="color:#000000;">Active</label>
                        <input id="status-2" class="magic-radio" type="radio" name="status" value="0" {{ $group_details->status == "0" ? "checked" : "" }}>
                        <label for="status-2" style="color:#000000;">Inactive</label>
                    </div>
                </div>
            </div>



            <div class="form-group">
                <label class="col-md-2 control-label"></label>
                <div class="col-md-2">
                    <input type="submit" class="btn btn-sm btn-block btn-primary" name="submit" value="UPDATE">
                </div>
            </div>
        </div>
    </form>
</div>
@stop

Modules/AdminUser/Resources/views/header_tab.blade.php
        <ul class="nav nav-tabs settings-header-nav">
            <li class="{{ isset($header_nav) && $header_nav == 'users' ? 'active' : '' }}">
                <a href="{{ route('admin.user.list') }}" style="color: black;font-weight: bold;">USERS</a>
            </li>

            <li class="{{ isset($header_nav) && $header_nav == 'groups' ? 'active' : '' }}">
                <a href="{{ route('admin.user.groups') }}" style="color: black;font-weight: bold;">GROUPS</a>
            </li>

        </ul>

Modules/AdminUser/Resources/views/password_reset.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row">
    <div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Change Password
                    <span class="required_fields" style="float: right;"><strong class="required_color">*</strong> These fields are required.</span>
                </h3>
            </div>

            <form action="{{ route('admin.user.password-reset.store') }}" method="POST" class="form-horizontal form-padding">
                <div class="panel-body">
                    {{ csrf_field() }}

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="admin-first-name">Current Password <span class="required_color">*</span></label>
                        <div class="col-md-10">
                            <input type="password" name="current_password" class="form-control" value="{{ old('current_password') }}" placeholder="Current Password" >
                            <small class="help-block text-danger">{{$errors->first('current_password')}}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="admin-first-name">New Password <span class="required_color">*</span></label>
                        <div class="col-md-10">
                            <input type="password" name="new_password" class="form-control" value="{{ old('new_password') }}" placeholder="New Password" >
                            <small class="help-block text-danger">{{$errors->first('new_password')}}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="admin-first-name">Confirm Password <span class="required_color">*</span></label>
                        <div class="col-md-10">
                            <input type="password" name="confirm_password" class="form-control" value="{{ old('confirm_password') }}" placeholder="Confirm Password" >
                            <small class="help-block text-danger">{{$errors->first('confirm_password')}}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-2">
                            <input type="submit" class="btn btn-sm btn-block btn-primary" name="submit" value="Reset Password">
                        </div>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>
@stop

Modules/AdminUser/Resources/views/profile.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row">
    <div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">
                    My Profile
                    <span class="required_fields" style="float: right;"><strong class="required_color">*</strong> These fields are required.</span>
                </h3>
            </div>

            <form action="{{ route('admin.user.profile.store') }}" method="POST" class="form-horizontal form-padding" enctype="multipart/form-data">
                <div class="panel-body">
                    @csrf
                    <input type="hidden" name="old_username" value="{{ $user->username }}">
                    <input type="hidden" name="old_email" value="{{ $user->email }}">
                    <div class="form-group">
                        <label class="col-md-2 control-label" for="admin-first-name">Full Name <span class="required_color">*</span></label>
                        <div class="col-md-10">
                            <div class="row">
                                <div class="col-md-4">
                                    <input type="text" id="admin-first-name" name="firstname" class="form-control" value="{{ $user->first_name }}" placeholder="First Name" >
                                    <small class="help-block text-danger">{{$errors->first('firstname')}}</small>
                                </div>
                                <div class="col-md-4">
                                    <input type="text" id="admin-first-name" name="middlename" class="form-control" value="{{ $user->middle_name }}" placeholder="Middle Name" >
                                    <small class="help-block text-danger">{{$errors->first('middlename')}}</small>
                                </div>
                                <div class="col-md-4">
                                    <input type="text" id="admin-last-name" name="lastname" class="form-control" value="{{ $user->last_name }}" placeholder="Last Name" >
                                    <small class="help-block text-danger">{{$errors->first('lastname')}}</small>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="demo-address-input">Username</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" name="username" value="{{ old('username') ? old('username') : $user->username }}">
                            <small class="help-block text-danger">{{$errors->first('username')}}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label" for="demo-address-input">Email</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" name="email" value="{{ old('email') ? old('email') : $user->email }}">
                            <small class="help-block text-danger">{{$errors->first('email')}}</small>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-2 pull-right">
                            <input type="submit" class="btn btn-sm btn-block btn-primary" value="Update Profile">
                        </div>
                    </div>
                </div>


            </form>
        </div>    
    </div>
</div>
@stop

Modules/AdminUser/Resources/views/user.blade.php
@extends('admin.layouts.master')
@section('content')

<div class="row">
    <div class="col">
                        @include('adminuser::header_tab')
                    <div class="panel">


                        <div class="panel-body">
                            <div class="row textright searchWrapperPosition">
                                <div class="col">
                                    <span class="text-main text-semibold">
                                       Users Management
                                    </span>
                                    <a href="{{ route('admin.user.add') }}" style="float: right;" class="btn btn-sm btn-sm btn-info addBtnAdminPanel"><i
                                                class="fa fa-plus"></i> Add New</a>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col">
                                    
                                    <table class="table table-striped table-bordered adminMgmtTable">
                                        <thead>
                                        <tr>
                                            <th>S.N</th>
                                            <th>User Type</th>
                                            <th>Full Name</th>
                                            <th>Username</th>
                                            <th>Email</th>
                                            <th>Phone</th>
                                            <th class="text-center">Status</th>
                                            <th>Operation</th>
                                        </tr>
                                        </thead>

                                        <tbody>

                                        @if( count($users) > 0 )
                                            <?php $i = 1; ?>
                                            @foreach($users as $ur)
                                                <tr>
                                                    <td align="center">{{ $i++ }} </td>
                                                    <td>
                                                        <?php
                                                        $grps_str = "";
                                                        $counter = 1;
                                                        ?>
                                                        @if( isset($ur->user_group) && count($ur->user_group) >0 )
                                                            @foreach($ur->user_group as $ugrp)
                                                                <?php
                                                                if ($counter != 1)
                                                                    $grps_str .= " | ";

                                                                $grps_str .= isset($ugrp->group_detail->name) ? $ugrp->group_detail->name : "";

                                                                $counter++;
                                                                ?>
                                                            @endforeach
                                                        @endif
                                                        <strong>{{ $grps_str }}</strong>
                                                    </td>
                                                    <td>{{ $ur->first_name." ".$ur->middle_name." ".$ur->last_name }}</td>
                                                    <td>{{ $ur->username }}</td>
                                                    <td>{{ $ur->email }}</td>
                                                    <td>{{ $ur->phone }}</td>
                                                    <td align="center">
                                                        {!! $ur->status ? "<span class='label label-success'>Active</span>" : "<span class='label label-danger'>Inactive</span>"!!}
                                                    </td>
                                                    <td width="150">
                                                        <a href="{{ route('admin.user.edit',[$ur->id]) }}"
                                                           class="btn btn-sm btn-info adminMgmtTableBtn" title="Edit User Group">
                                                            <i class="fa fa-edit"></i>
                                                        </a>

                                                        <a href="#" class="btn btn-sm btn-primary adminMgmtTableBtn btnResetPass"
                                                           title="Reset Password"
                                                           data-user-id="{{ $ur->id }}"
                                                           data-user-name="{{ $ur->first_name." ".$ur->middle_name." ".$ur->last_name }}"
                                                           data-user-email="{{ $ur->email }}">
                                                            <i class="fas fa-key"></i>
                                                        </a>


                                                        @if ( isset( $ur->user_is_superadmin ) && $ur->user_is_superadmin->count() == 0 )
                                                            <a href="#" class="btn btn-sm btn-danger btn-delete"
                                                               data-id="{{ $ur->id }}"
                                                               data-toggle="modal"
                                                               data-target="#delete-modal">
                                                                <i class="fa fa-trash"></i>
                                                            </a>
                                                        @endif
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @else
                                            <tr>
                                                <td align="center" colspan="10">
                                                    <em>No data available in table...</em>
                                                </td>
                                            </tr>
                                        @endif
                                        </tbody>
                                    </table>
                                </div>
                            </div>

                        </div>
                    </div>
    </div>
</div>

    <!-- Modal reset Password -->
    <div id="reset-password-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-md">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><i class="pci-cross pci-circle"></i>
                    </button>
                    <h4 class="modal-title" id="myLargeModalLabel">Reset Password</h4>
                </div>

                <form class="form-horizontal" action="{{ route('admin.user.password-reset-user') }}" method="POST">
                    {{ csrf_field() }}
                    <input type="hidden" name="_user_id" id="_user_id" value="">
                    <div class="modal-body">
                        <div class="bootbox-body">
                            <div class="row">
                                <div class="col-md-12">


                                    <div class="form-group">
                                        <label class="col-md-3 control-label" for="name">Customer Name: </label>
                                        <div class="col-md-6" style="text-align: left;padding: 7px 0 0 0;">
                                            <label id="_user_name" style="font-weight: 600;"></label>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label" for="name">Email: </label>
                                        <div class="col-md-6" style="text-align: left;padding: 7px 0 0 0;">
                                            <label id="_user_email" style="font-weight: 600;"></label>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label" for="name">Reset Password</label>
                                        <div class="col-md-6">
                                            <input name="st_user_password" type="password" class="form-control input-md"
                                                   value="" required>
                                        </div>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-sm btn-primary">Reset</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
    @include('admin.elements.delete-modal')
@stop

@push('scripts')
<script type="text/javascript">
    $(document).ready(function () {
        $('[data-toggle="tooltip"]').tooltip();

        $('.btnResetPass').click(function () {

            var user_id = $(this).attr('data-user-id');
            if (user_id == '' || user_id == null) {
                return false;
            }
            var user_name = $(this).attr('data-user-name');
            var user_email = $(this).attr('data-user-email');

            $('#_user_id').val(user_id);
            $('#_user_name').html(user_name);
            $('#_user_email').html(user_email);

            $('#reset-password-modal').modal({show: true});
        });
    });

    $(document).on('click','.btn-delete', function () {
        var route = '{{ route('admin.user.destroy', ':id') }}';

        route = route.replace(':id', $(this).attr('data-id'));

        $('#delete-modal').find('form').attr('action', route);
        $('#delete-modal').modal('show');

        $('#delete-final').click(function (e) {
            $(this).attr('disabled',true);
            $(this).html('<i class="fas fa-spinner fa-spin"></i> Please wait...');
            $(this).closest('form').submit();
        });
    });
</script>
@endpush