Modules/AdminContent/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('admin/welcome-note', 'AdminContentController@welcomeNote')->middleware('auth:admin')->name('admin.welcome-note')->middleware('can:view-contents');
Route::group(['prefix' => 'admin/contents', 'as' => 'admin.', 'middleware' => 'auth:admin'], function() {

    Route::get('/', 'AdminContentController@index')
        ->name('contents')
        ->middleware('can:view-contents');

    Route::get('/create', 'AdminContentController@create')
        ->name('contents.create')
        ->middleware('can:create-contents');

    Route::post('/create', 'AdminContentController@store')
        ->name('contents.store')
        ->middleware('can:create-contents');

    Route::get('/{id}/edit', 'AdminContentController@edit')
        ->name('contents.edit')
        ->middleware('can:edit-contents');

    Route::post('/{id}/edit', 'AdminContentController@update')
        ->name('contents.update')
        ->middleware('can:edit-contents');

    Route::post('/welcome-note/update', 'AdminContentController@updateWelcome')
        ->name('contents.update-welcome')
        ->middleware('can:edit-contents');

    Route::post('/{id}/delete', 'AdminContentController@destroy')
        ->name('contents.destroy')
        ->middleware('can:delete-contents');
});

Modules/AdminContent/Resources/views/create.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row">
	<div class="co">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Add Page
                    <button class="btn btn-sm btn-primary pull-right panel-btn" onclick="window.history.go(-1);">
                        <i class="fas fa-long-arrow-alt-left"></i> Back
                    </button>
                </h3>
            </div>

            <!--Horizontal Form-->
            <!--===================================================-->
            <form action="{{ route('admin.contents.store') }}" method="POST" class="form-horizontal" enctype="multipart/form-data">
                @csrf
                <div class="panel-body">
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="input-title">Title <span class="required_color">*</span></label>
                        <div class="col-sm-9">
                            <input type="text" placeholder="" value="{{ old('title') }}" name="title" id="input-title" class="form-control">
                            <small class="help-block text-danger">{{ $errors->first('title')}}</small>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
	                    <label class="col-md-2 control-label">Is Published</label>
	                    <div class="col-md-9">
	                        <div class="radio">

	                            <!-- Inline radio buttons -->
	                            <input id="input-status" class="magic-radio" type="radio" name="status" value="1" <?= ((old('status') == 1)? 'checked':''); ?>>
	                            <label for="input-status">Yes</label>

	                            <input id="input-status-2" class="magic-radio" value="0" type="radio" name="status" <?= ((old('status') == 0)? 'checked':''); ?>>
	                            <label for="input-status-2">No</label>
	                        </div>
	                    </div>
	                </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-type">Type <span class="required_color">*</span></label>
                        <div class="col-sm-9">
                            <select id="input-type-select" name="type" class="form-control">
                                <option value="1" <?= ((old('type') == 1)? 'selected':''); ?>>Text</option>
                                <option value="2" <?= ((old('type') == 2)? 'selected':''); ?>>Image</option>
                                <option value="3" <?= ((old('type') == 3)? 'selected':''); ?>>Video</option>
                                <option value="4" <?= ((old('type') == 4)? 'selected':''); ?>>Power Point</option>
                                <option value="5" <?= ((old('type') == 5)? 'selected':''); ?>>PDF</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('type_file') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="demo-hor-inputemail"></label>
                        <div class="col-sm-9">
                            <div id="type-file" style="display:none;margin-top: 5px;">
                                <input type="file" id="input-type-file" name="type_file" class="form-control">
                            </div>
                            <small class="help-block text-danger">{{ $errors->first('type_file')}}</small>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="demo-hor-inputpass">Content Body <span class="required_color">*</span></label>
                        <div class="col-sm-9">
	                        <textarea name="body" id="input-body" class="form-control ckeditor">{!! old('body') !!}</textarea>
                            <small class="help-block text-danger">{{ $errors->first('body') }}</small>
                        </div>
                    </div>
                </div>
                <div class="panel-footer text-right">
                	<div class="row">
		                <div class="col-lg-11">
		                    <button class="btn btn-mint" type="submit">Create</button>
		                </div>
                	</div>
                </div>
            </form>
            <!--===================================================-->
            <!--End Horizontal Form-->

        </div>
    </div>
</div>
@endsection
@push('scripts')
<script type="text/javascript">
    $(function() {
        if ($("#input-type-select").val() == 1) {
            $("#type-file").hide();
        } else {
            $("#type-file").show();
        }
        $("#input-type-select").on('change', function(event) {
            var val = $(this).val();
            if (val != 1) {
                $("#type-file").show();
            } else {
                $("#type-file").hide();
            }
        });
    });
</script>
@endpush

Modules/AdminContent/Resources/views/edit.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row">
	<div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Edit Page
                	<button class="btn btn-sm btn-primary pull-right panel-btn" onclick="window.history.go(-1);">
                	    <i class="fas fa-long-arrow-alt-left"></i> Back
                	</button>
                </h3>
            </div>

            <!--Horizontal Form-->
            <!--===================================================-->
            <form action="{{ route('admin.contents.update',$content->id) }}" enctype="multipart/form-data" method="POST" class="">
                @csrf
                <div class="panel-body">
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="input-title">Title <span class="required_color">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="" value="{{ old('title',$content->title) }}" name="title" id="input-title" class="form-control">
                            <small class="help-block text-danger">{{ $errors->first('title')}}</small>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
	                    <label class="col-md-2 control-label">Is Published</label>
	                    <div class="col-md-9">
	                        <div class="radio">
	
	                            <!-- Inline radio buttons -->
	                            <input id="input-status" class="magic-radio" type="radio" name="status" value="1" {{ $content->status ? 'checked' :'' }}>
	                            <label for="input-status">Yes</label>
	
	                            <input id="input-status-2" class="magic-radio" value="0" type="radio" name="status" {{ $content->status == 0 ? 'checked' : '' }}>
	                            <label for="input-status-2">No</label>
	                        </div>
	                    </div>
	                </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-type">Type <span class="required_color">*</span></label>
                        <div class="col-sm-10">
                            <select id="input-type-select" name="type" class="form-control" id="">
                                <option value="1" {{ old('type',$content->type) == 1 ? 'selected' :'' }}>Text</option>
                                <option value="2" {{ old('type',$content->type) == 2 ? 'selected' :'' }}>Image</option>
                                <option value="3" {{ old('type',$content->type) == 3 ? 'selected' :'' }}>Video</option>
                                <option value="4" {{ old('type',$content->type) == 4 ? 'selected' :'' }}>Power Point</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('type_file') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="input-type-file"></label>
                        <div class="col-sm-10">
                            <div id="type-file" style="margin-top: 5px;">
                                <p id="type-file-name">{{ $content->type_file_name }}</p>
                                <input id="input-type-file" type="file" name="type_file" class="form-control">
                            </div>
                            <small class="help-block text-danger">{{ $errors->first('type_file')}}</small>
                        </div>
                    </div>
                    <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="input-body">Content Body <span class="required_color">*</span></label>
                        <div class="col-sm-10">
	                        <textarea name="body" id="input-body" class="form-control ckeditor">{!! old('body',$content->body) !!}</textarea>
                            <small class="help-block text-danger">{{ $errors->first('body') }}</small>
                        </div>
                    </div>
                </div>
                <div class="panel-footer text-right">
                    <div class="form-group">
                        <button class="btn btn-mint" type="submit">Update</button>
                    </div>
                </div>
            </form>
            <!--===================================================-->
            <!--End Horizontal Form-->

        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    $(function() {
        if ($("#input-type-select").val() == 1) {
            $("#type-file").hide();
        } else {
            $("#type-file").show();
        }
        $("#input-type-select").on('change', function(event) {
            var val = $(this).val();
            if (val != 1) {
                $("#type-file").show();
            } else {
                $("#type-file").hide();
            }
        });
        
        $("#input-type-file").on('change', function(event) {
            var fullPath=$(this).val(); 
            if (fullPath) {
                var startIndex = (fullPath.indexOf('\\') >= 0 ? fullPath.lastIndexOf('\\') : fullPath.lastIndexOf('/'));
                var filename = fullPath.substring(startIndex);
                if (filename.indexOf('\\') === 0 || filename.indexOf('/') === 0) {
                    filename = filename.substring(1);
                }
                $("#type-file-name").html(filename);
            }
        });
    });
</script>
@endpush

Modules/AdminContent/Resources/views/index.blade.php
@extends('admin.layouts.master')
@section('content')
<!-- @if(Session::get('success_message'))
    <div class="alert alert-success containerAlert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        {{ Session::get('success_message') }}
    </div>
@endif
@if(Session::get('error_message'))
    <div class="alert alert-danger containerAlert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        {{ Session::get('error_message') }}
    </div>
@endif -->
<div class="row">
    <div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Pages Management
                    <a href="{{ route('admin.contents.create') }}" class="btn btn-primary btn-sm panel-btn pull-right"><i class="fa fa-plus"></i> Add page</a>
                </h3>
            </div>

            <!-- Striped Table -->
            <!--===================================================-->
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
	                            <th>S.N</th>
	                            <th>Title</th>
                                <th>Type</th>
	                            <th>Published</th>
	                            <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	@forelse($contents as $content)
                    	    <tr>
                    	        <td>{{ $loop->iteration }}</td>
                    	        <td>{{ $content->title }}</td>
                    	        <td>{{ $content->type_name }}</td>
                    	        <td>{!! $content->status ? "<span class='label label-success'>Active</span>" : "<span class='label label-danger'>Inactive</span>"!!}</td>
                    	        <td>
                    	            <a href="{{ route('admin.contents.edit',$content->id) }}" class="btn btn-sm btn-primary" title="Edit">
                    	                <i class="fas fa-edit"></i>
                    	            </a>
                    	            <a href="#" title="Remove" class="btn btn-sm btn-danger btn-delete"
                    	               data-toggle="modal"
                    	               data-id="{{ $content->id }}"
                    	               data-target="#delete-modal">
                    	                <i class="fas fa-trash"></i>
                    	            </a>
                    	        </td>
                    	    </tr>
                        	@empty
                    	    <tr>
                    	        <td colspan="5">
                    	            <em>No data available in table ...</em>
                    	        </td>
                    	    </tr>
                        	@endforelse
                        </tbody>
                    </table>
                </div>
            </div>
            <!--===================================================-->
            <!-- End Striped Table -->

        </div>
    </div>
    @include('admin.elements.delete-modal')
</div>
@endsection
@push('scripts')
    <script type="text/javascript">
        $(document).on('click','.btn-delete', function () {
            var route = '{{ route('admin.contents.destroy', ':id') }}';

            route = route.replace(':id', $(this).attr('data-id'));

            $('#delete-modal').find('form').attr('action', route);
            $('#delete-modal').modal('show');

            $('#delete-final').click(function (e) {
                $(this).attr('disabled',true);
                $(this).html('<i class="fas fa-spinner fa-spin"></i> Please wait...');
                $(this).closest('form').submit();
            });
        });
    </script>
@endpush

Modules/AdminContent/Resources/views/welcome-note.blade.php
@extends('admin.layouts.master')
@section('content')
<div class="row">
	<div class="col">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Welcome Note
                	<button class="btn btn-sm btn-primary pull-right panel-btn" onclick="window.history.go(-1);">
                	    <i class="fas fa-long-arrow-alt-left"></i> Back
                	</button>
                </h3>
            </div>

            <!--Horizontal Form-->
            <!--===================================================-->
            <form action="{{ route('admin.contents.update-welcome') }}" enctype="multipart/form-data" method="POST" class="">
                @csrf
                <div class="panel-body">
                    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="input-title">Title <span class="required_color">*</span></label>
                        <div class="col-sm-10">
                            <input type="text" placeholder="" value="{{ old('title',$content->title) }}" name="title" id="input-title" class="form-control">
                            <small class="help-block text-danger">{{ $errors->first('title')}}</small>
                        </div>
                    </div>
                    <!-- <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                                            <label class="col-md-2 control-label">Is Published</label>
                                            <div class="col-md-9">
                                                <div class="radio">
                        
                                                    Inline radio buttons
                                                    <input id="input-status" class="magic-radio" type="radio" name="status" value="1" {{ $content->status ? 'checked' :'' }}>
                                                    <label for="input-status">Yes</label>
                        
                                                    <input id="input-status-2" class="magic-radio" value="0" type="radio" name="status" {{ $content->status == 0 ? 'checked' : '' }}>
                                                    <label for="input-status-2">No</label>
                                                </div>
                                            </div>
                                        </div> -->
                    <!-- <div class="form-group">
                        <label class="col-sm-2 control-label" for="input-type">Type <span class="required_color">*</span></label>
                        <div class="col-sm-10">
                            <select id="input-type-select" name="type" class="form-control" id="">
                                <option value="1" {{ old('type',$content->type) == 1 ? 'selected' :'' }}>Text</option>
                                <option value="2" {{ old('type',$content->type) == 2 ? 'selected' :'' }}>Image</option>
                                <option value="3" {{ old('type',$content->type) == 3 ? 'selected' :'' }}>Video</option>
                                <option value="4" {{ old('type',$content->type) == 4 ? 'selected' :'' }}>Power Point</option>
                            </select>
                        </div>
                    </div> -->
                    <!-- <div class="form-group{{ $errors->has('type_file') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="input-type-file"></label>
                        <div class="col-sm-10">
                            <div id="type-file" style="margin-top: 5px;">
                                <p id="type-file-name">{{ $content->type_file_name }}</p>
                                <input id="input-type-file" type="file" name="type_file" class="form-control">
                            </div>
                            <small class="help-block text-danger">{{ $errors->first('type_file')}}</small>
                        </div>
                    </div> -->
                    <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                        <label class="col-sm-2 control-label" for="input-body">Content Body <span class="required_color">*</span></label>
                        <div class="col-sm-10">
	                        <textarea name="body" id="input-body" class="form-control ckeditor">{!! old('body',$content->body) !!}</textarea>
                            <small class="help-block text-danger">{{ $errors->first('body') }}</small>
                        </div>
                    </div>
                </div>
                <div class="panel-footer text-right">
                    <button class="btn btn-mint" type="submit">Update</button>
                </div>
            </form>
            <!--===================================================-->
            <!--End Horizontal Form-->

        </div>
    </div>
</div>
@endsection